name: flappy_bird
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^2.7.0
  http: ^1.1.0
  path_provider: ^2.1.1
  rating_dialog: ^2.0.4
  audioplayers: ^5.2.0
  smooth_star_rating_null_safety: ^1.0.4+2
  share_plus: ^7.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
flutter:
  uses-material-design: true
  assets:
    - assets/pics/
    - assets/audio/
  fonts:
    - family: Magic4
      fonts:
        - asset: assets/fonts/DiloWorld-mLJLv.ttf